package com.daydeal_admin;

public class Temp {
    public static String appttitle = "DayDealAdmin";
    public static String edit_cashback="";
    public static String edit_catogeryname="";
    public static String edit_deliverycharge="";
    public static String edit_dscription="";
    public static String edit_imgsig="0";
    public static String edit_imgsig1 = "0";
    public static String edit_itemkeywords="";
    public static String edit_itemname="";
    public static String edit_latitude="";
    public static String edit_longitude="";
    public static String edit_mobile1="";
    public static String edit_mobile2="";
    public static String edit_offerprice="";
    public static String edit_orginalprice="";
    public static String edit_ownername="";
    public static String edit_place="";
    public static String edit_productid="";
    public static String edit_shopid="";
    public static String edit_shopname="";
    public static String foldername = "DayDeal_Admin";
    public static String img_imgsig="";
    public static String img_link="";
    public static String img_title="";
    public static int isproductedit = 0;
    public static int isshopedit = 0;
    public static int markettingstaffedit = 0;
    public static String mobile1="";
    public static String mobile2="";
    public static String mrktid="";
    public static String name="";
    public static String nointernet = "Please make sure your internet connection is active";
    public static String packagename = BuildConfig.APPLICATION_ID;
    public static String place="";
    public static int productcatedit = 0;
    public static String productcateditsn="";
    public static String profileimgsig="";
    public static String proofimgsig="";
    public static String tempproblem = "Temporary Problem ! Please try later";
    public static String weblink = "http://apistatuschinthakal.in/daydeal/";
}
